#
# Copyright (C) Guangzhou FriendlyARM Computer Tech. Co., Ltd.
# (http://www.friendlyarm.com)
#

obj-y += $(BOARD).o eth_setup.o

obj-$(CONFIG_USB_GADGET) += dwc2_otg.o
obj-$(CONFIG_CMD_FASTBOOT) += part.o fastboot.o

